exclude: ".yarn/|yarn.lock|static"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.17.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.5"
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args: [--list-different, --no-semi, "--trailing-comma=es5"]
        exclude: "^conf/|.*\\.html$"
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.1.0"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.7.3"]
